/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prolog.vistas;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Map;
import java.util.StringTokenizer;
import org.jpl7.Query;
import org.jpl7.Term;
import prolog.conectores.Imagen;
import prolog.conectores.XmlReader;

/**
 *
 * @author Antonio
 */
public class DetalleDieta extends javax.swing.JFrame {

    /**
     * Creates new form DetalleDieta
     */
    
    private XmlReader xmlUser;
    private String dietas;
    
    public DetalleDieta() {
        initComponents();
    }

    public void setXml(XmlReader xml){
        this.xmlUser = xml;
        printDieta();
        showD();
    }
    
    private void showD(){
        String diet = "";
        int flg;
        Calendar calendario = Calendar.getInstance();
        int hora =calendario.get(Calendar.HOUR_OF_DAY);
        
        if(hora < 8)
            flg = 1;
        else if(hora > 8 && hora < 12)
            flg = 2;
        else if(hora > 12 && hora < 14)
            flg = 3;
        else if(hora > 14 && hora < 18)
            flg = 4;
        else
            flg = 5;
        
        StringTokenizer tokens=new StringTokenizer(dietas,",");
        int con = 0;
	while(tokens.hasMoreTokens() && con < flg){
            diet = tokens.nextToken();
            con++;
        }
       diet = diet.trim();
       XmlReader xml = new XmlReader("./src/Recursos/Dietas/"+diet+".xml");
       jTextArea1.setText(xml.read("p"));
       jLabel1.setText(xml.read("Titulo").trim());
       System.out.println(xml.read("imagen").trim());
       Imagen img = new Imagen(jPanel1,xml.read("imagen").trim());
       jPanel1.add(img).repaint();
    }
    
    private void printDieta(){
        String fechadieta = xmlUser.read("fechadieta").trim();
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        Date date = new Date();
        if(fechadieta.equals(dateFormat.format(date))){
            dietas = xmlUser.read("dieta").trim();
        }
        else{
            xmlUser.replace("fechadieta", dateFormat.format(date));
            String edad = xmlUser.read("edad").trim();
            String sexo = xmlUser.read("sexo").trim();
            String peso = xmlUser.read("peso").trim();
            String altura = xmlUser.read("altura").trim();
            String mes = xmlUser.read("fechareg").trim().substring(3,5);
            if(Integer.parseInt(mes)>Integer.parseInt(dateFormat.format(date).substring(3,5)))
                mes = "1";
            else
                mes = "2";
            String dis = xmlUser.read("disponibilidad").trim();
            dis = Integer.toString(Integer.parseInt(dis)-2);
            Query q1 = new Query("consult('dieta.pl')");
            System.out.println(q1.hasSolution() ? "Conexión correcta" : "Conexión fallida");
            //se(MES,MET,ACFIS,SEX,PESO,ALT,EDAD,LISTA)
            Query q2 = new Query("se("+mes+",2,"+dis+","+sexo+","+peso+","+altura+","+edad+",X).");
            String tmp = "";
            while(q2.hasMoreSolutions()){
                Map<String, Term> sol = q2.nextSolution();
                tmp += sol.get("X")+"\n";
            }
            tmp = tmp.trim();
            tmp = tmp.replaceAll("[^\\w,]","");
            xmlUser.replace("dieta",tmp);
            xmlUser.save();
            dietas=tmp;
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 317, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetalleDieta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetalleDieta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetalleDieta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetalleDieta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetalleDieta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
