/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prolog.vistas;

import org.jpl7.Query;
import prolog.conectores.XmlReader;
import prolog.conectores.XmlWriter;



/**
 *
 * @author Antonio
 */
public class Principal extends javax.swing.JFrame {

    private static String user;
    private static XmlReader xmlUser;
    private static int rutinaH = 0; //Rutina actual
    private static int disponibilidad = 0; //Dias a la semana
    private static String musculosDia = "";
    private static String musculo ="";
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        verDetalleRutinas = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mostrarRutinaDia = new javax.swing.JTextArea();
        jToggleButton2 = new javax.swing.JToggleButton();
        registroActividad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Bienvenido a SE-Fitness");

        verDetalleRutinas.setText("Detalles de la Rutina");
        verDetalleRutinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verDetalleRutinasActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Rutina del Día");

        mostrarRutinaDia.setColumns(20);
        mostrarRutinaDia.setRows(5);
        jScrollPane1.setViewportView(mostrarRutinaDia);

        jToggleButton2.setText("Dieta del Día");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        registroActividad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        registroActividad.setText("Registrar rutina actual");
        registroActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroActividadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(verDetalleRutinas, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(registroActividad)
                                    .addGap(191, 191, 191))))))
                .addGap(0, 53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(registroActividad)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton2)
                    .addComponent(verDetalleRutinas))
                .addGap(107, 107, 107))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registroActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroActividadActionPerformed
        // TODO add your handling code here:
                        
        //Leemos los datos del xml
        String nombreR = xmlUser.read("nombre");
        String edadR = xmlUser.read("edad");
        String sexoR = xmlUser.read("sexo");
        String pesoR = xmlUser.read("peso");
        String alturaR = xmlUser.read("altura");
        String dispR = xmlUser.read("disponibilidad");
        String rutinaSR = xmlUser.read("rutinaSemanal");
        String tipoCR = xmlUser.read("tipocuerpo");
        String rutinaAR = xmlUser.read("rutinaAnterior");
        String abdomenR = xmlUser.read("sigueAbdomen"); //Estatus del abdomen
        
        nombreR = nombreR.trim();
        edadR = edadR.trim();
        sexoR = sexoR.trim();
        pesoR = pesoR.trim();
        alturaR = alturaR.trim();
        dispR = dispR.trim();
        rutinaSR = rutinaSR.trim();
        tipoCR = tipoCR.trim();
        rutinaAR = rutinaAR.trim();
        abdomenR = abdomenR.trim();
        
        System.out.println("Usuario:");
        System.out.println(nombreR);
        System.out.println(edadR);
        System.out.println(sexoR);
        System.out.println(pesoR);
        System.out.println(alturaR);
        System.out.println(dispR);
        System.out.println(rutinaSR);
        System.out.println(tipoCR);
        System.out.println(rutinaAR);
        System.out.println("Rutina actual: " + rutinaH);
        System.out.println("Abdomen: " + abdomenR);
        //Fin de lectura de datos del xml
        
        //Escritura del nuevo archivo
        XmlWriter writer;
        try{
        writer = new XmlWriter("./src/Recursos/Usuarios/" + nombreR + ".xml");
        writer.add("nombre", nombreR);
        writer.add("edad", edadR);
        writer.add("sexo", sexoR);
        writer.add("peso", pesoR);
        writer.add("altura", alturaR);
        writer.add("disponibilidad", dispR);
        writer.add("rutinaSemanal", rutinaSR);
        writer.add("tipocuerpo", tipoCR);
        writer.add("rutinaAnterior",String.valueOf(rutinaH));
        
        int abdomen = Integer.valueOf(abdomenR);
        if ( abdomen == 1)
            writer.add("sigueAbdomen", "0");
        else
            writer.add("sigueAbdomen", "1");
        
        
        if(writer.write()){
            mostrarRutinaDia.setText("Se registró exitosamente tu rutina actual! \n" + "Te espero mañana");
            System.out.println("Se registró el día: " + rutinaH);
        }
        else
            mostrarRutinaDia.setText("No se registró tu rutina! \n" + "Intenta otra vez por favor");
        } catch(Exception e){
            System.out.println("Error al registrar rutina...");
        }
        //Fin de escritura del nuevo archivo

    }//GEN-LAST:event_registroActividadActionPerformed

    private void verDetalleRutinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verDetalleRutinasActionPerformed
        // TODO add your handling code here:
        DetalleRutinas detalles = new DetalleRutinas();
        detalles.setVisible(true);       
        
    }//GEN-LAST:event_verDetalleRutinasActionPerformed

    private void mostrarDatosUser (){
            
        //Leemos los datos del xml
        String nombreR = xmlUser.read("nombre");
        String edadR = xmlUser.read("edad");
        String sexoR = xmlUser.read("sexo");
        String pesoR = xmlUser.read("peso");
        String alturaR = xmlUser.read("altura");
        String dispR = xmlUser.read("disponibilidad");
        String rutinaSR = xmlUser.read("rutinaSemanal");
        String tipoCR = xmlUser.read("tipocuerpo");
        String rutinaAR = xmlUser.read("rutinaAnterior");
        String abdomenR = xmlUser.read("sigueAbdomen");
        
        nombreR = nombreR.trim();
        edadR = edadR.trim();
        sexoR = sexoR.trim();
        pesoR = pesoR.trim();
        alturaR = alturaR.trim();
        dispR = dispR.trim();
        rutinaSR = rutinaSR.trim();
        tipoCR = tipoCR.trim();
        rutinaAR = rutinaAR.trim();
        abdomenR = abdomenR.trim();
        
        System.out.println("Usuario:");
        System.out.println(nombreR);
        System.out.println(edadR);
        System.out.println(sexoR);
        System.out.println(pesoR);
        System.out.println(alturaR);
        System.out.println(dispR);
        System.out.println(rutinaSR);
        System.out.println(tipoCR);
        System.out.println("Rutina anterior:" + rutinaAR);
        System.out.println("Rutina actual: " + rutinaH);
        System.out.println("Abdomen: " + abdomenR);
        //Fin de lectura de datos del xml
    
    }
    
    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
                
            }
        });
        
    }

    public void iniciarValores(String usuario, XmlReader xml ){
        
        user = usuario;
        xmlUser = xml;
        
        mostrarDatosUser();
        String disp1 = xml.read("disponibilidad");
        String rutinaA = xml.read("rutinaAnterior"); //Ultima rutina hecha
        String abdomen = xml.read("sigueAbdomen"); //Estatus del abdomen
        String tipoCuerpo = xml.read("tipocuerpo"); //Tipo del cuerpo
        String meta ="";
        
        int estAbd = 0;
        
        try {
            disp1 = disp1.trim();
            rutinaA = rutinaA.trim();
            abdomen = abdomen.trim();
            disponibilidad = Integer.valueOf(disp1);
            rutinaH = Integer.valueOf(rutinaA);
            estAbd = Integer.valueOf(abdomen);
            
        }catch (NumberFormatException e){
            System.out.println("not a number"); 
        } 
        
        rutinaH ++;
        System.out.println("Incremento de rutinaA: " + rutinaH);
        if(rutinaH > disponibilidad)  //Si ya hizo todoas las rutinas semanales, reiniciamos.
            rutinaH = 1;
        
        //Consultamos rutina actual...
        try{
            String rutinas = xml.read("rutinaSemanal");
            rutinas = rutinas.replace("\n", "");
            XmlReader xmlR = new XmlReader("./src/Recursos/Rutinas/" + rutinas + ".xml");
            musculosDia = xmlR.read("dia" + rutinaH);
        }
        catch(Exception e){
            
        }
        //Fin de consulta de rutina actual...    
        
        //Consultamos su meta por tipo de cuerpo
        String mensaje = "";
        try{
            String conexion= "consult('bd.pl')";
            Query con= new Query(conexion);
            System.out.println(conexion + " " + (con.hasMoreSolutions()? "Aceptado": "False"));
            
            String consulta = "meta(" + tipoCuerpo + ",X).";
            Query ejecutar = new Query(consulta);
            
            if(ejecutar.hasSolution()){
                meta= ejecutar.oneSolution().get("X").toString();
                //tipoCuerpo = tipoCuerpo.trim();
                System.out.println("Tipo de cuerpo-mensaje: " + tipoCuerpo + "-" + meta);
                XmlReader reader = new XmlReader("./src/Recursos/Metas/metas.xml");
                mensaje = reader.read(meta);
            }
            else{
                System.out.println("No econtró la meta para el tipo de cuerpo");
            }
            
        }catch(Exception e){
        }
        //Fin de consulta de meta por tipo de cuerpo
        tipoCuerpo = tipoCuerpo.trim();
        
        if(estAbd == 1)
            mostrarRutinaDia.setText("Hoy te toca:" + musculosDia + "y también: " + "abdomen\n\n¡¡IMPORTANTE!!\n" + mensaje );
        else{
            if ( tipoCuerpo.equals("endomorfo"))
                mostrarRutinaDia.setText("Hoy te toca:" + musculosDia + "Para bajar de peso has 30 minutos de cardio" + "\n\n¡¡IMPORTANTE!!\n" + mensaje);
            else
                mostrarRutinaDia.setText("Hoy te toca:" + musculosDia + "\n\n¡¡IMPORTANTE!!\n" + mensaje);
        }
        
    }
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JTextArea mostrarRutinaDia;
    private javax.swing.JButton registroActividad;
    private javax.swing.JToggleButton verDetalleRutinas;
    // End of variables declaration//GEN-END:variables
}
