/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prolog.vistas;

import org.jpl7.Query;

/**
 *
 * @author Zafiro
 */
public class testTipoCuerpo extends javax.swing.JFrame {

    /**
     * Creates new form testTipoCuerpo
     */
    private String tipoCuerpo;
    
    public testTipoCuerpo() {
        this.tipoCuerpo="";
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        Contenedor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        opcionesP1 = new javax.swing.JComboBox<String>();
        opcionesP2 = new javax.swing.JComboBox<String>();
        opcionesP3 = new javax.swing.JComboBox<String>();
        opcionesP4 = new javax.swing.JComboBox<String>();
        jLabel8 = new javax.swing.JLabel();
        opcionesP5 = new javax.swing.JComboBox<String>();
        jLabel9 = new javax.swing.JLabel();
        opcionesP6 = new javax.swing.JComboBox<String>();
        jLabel10 = new javax.swing.JLabel();
        opcionesP7 = new javax.swing.JComboBox<String>();
        jLabel11 = new javax.swing.JLabel();
        opcionesP8 = new javax.swing.JComboBox<String>();
        jLabel12 = new javax.swing.JLabel();
        opcionesP9 = new javax.swing.JComboBox<String>();
        jLabel13 = new javax.swing.JLabel();
        opcionesP10 = new javax.swing.JComboBox<String>();
        jLabel14 = new javax.swing.JLabel();
        opcionesP11 = new javax.swing.JComboBox<String>();
        jLabel15 = new javax.swing.JLabel();
        opcionesP12 = new javax.swing.JComboBox<String>();
        enviarDatos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resTipoCuerpo = new javax.swing.JTextArea();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Test para determinar el tipo de cuerpo");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Elija la respusta que mejor se adapte a usted:");

        jLabel3.setText("1. Mi cuerpo tiende a:");

        jLabel4.setText("2. Mi cuerpo se ve:");

        jLabel5.setText("3. Mi estructura osea es:");

        jLabel6.setText("4. De niño(a) era:");

        opcionesP1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Elige una opción", "Ser demasiado flaco", "Ser delgado y musculado", "Acumular demasiada grasa" }));
        opcionesP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionesP1ActionPerformed(evt);
            }
        });

        opcionesP2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Elige una opción", "Largo y sin mucho relieve", "Cuadrado (hombres) / en forma de X es decir cintura estrecha (mujeres).", "Redondo y suave (hombres) / en forma de pera (mujeres)" }));
        opcionesP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionesP2ActionPerformed(evt);
            }
        });

        opcionesP3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Elige una opción", "Pequeña y fragil", "Mediana", "Grande" }));
        opcionesP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionesP3ActionPerformed(evt);
            }
        });

        opcionesP4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Elige una opción", "Demasiado flaco", "Normal", "Gordito (a)" }));
        opcionesP4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionesP4ActionPerformed(evt);
            }
        });

        jLabel8.setText("5. Mi ritmo de vida es:");

        opcionesP5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Elige una opción", "Preocupado", "Dimámico", "Tranquilo y reposado" }));
        opcionesP5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionesP5ActionPerformed(evt);
            }
        });

        jLabel9.setText("6. Mi nivel de actividad es:");

        opcionesP6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Elige una opción", "Hiperactivo", "Muy activo", "Sedentario" }));
        opcionesP6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionesP6ActionPerformed(evt);
            }
        });

        jLabel10.setText("7. Las personas me dicen que:");

        opcionesP7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Elige una opción", "Debo engordar", "Estoy bien", "Debo perder peso" }));
        opcionesP7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionesP7ActionPerformed(evt);
            }
        });

        jLabel11.setText("8.Al rodear la muñeca con el dedo medio y pulgar de tu otra mano:");

        opcionesP8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Elige una opción", "Un dedo se pone por encima del otro", "Apenas se tocan", "Los dos dedos no se tocan", " ", " " }));
        opcionesP8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionesP8ActionPerformed(evt);
            }
        });

        jLabel12.setText("9. Mi metabilismo es:");

        opcionesP9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Elige una opción", "Demasiado rapido", "Normal", "Lento", " ", " " }));
        opcionesP9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionesP9ActionPerformed(evt);
            }
        });

        jLabel13.setText("10. Sobre mi peso:");

        opcionesP10.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Elige una opción", "Sufro para subir de peso", "Gano y pierdo peso fácilmente", "Gano peso fácilmente pero me cuesta perderlo", " ", " " }));
        opcionesP10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionesP10ActionPerformed(evt);
            }
        });

        jLabel14.setText("11. Tengo habre:");

        opcionesP11.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Elige una opción", "Raramente", "A la hora de comer", "Todo el tiempo", " ", " " }));
        opcionesP11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionesP11ActionPerformed(evt);
            }
        });

        jLabel15.setText("12.  La gente me podría describir como una persona:");

        opcionesP12.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Elige una opción", "Intelectual", "Física", "Emocional" }));
        opcionesP12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionesP12ActionPerformed(evt);
            }
        });

        enviarDatos.setText("Calcular mi tipo de cuerpo");
        enviarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarDatosActionPerformed(evt);
            }
        });

        resTipoCuerpo.setColumns(20);
        resTipoCuerpo.setRows(5);
        jScrollPane1.setViewportView(resTipoCuerpo);

        javax.swing.GroupLayout ContenedorLayout = new javax.swing.GroupLayout(Contenedor);
        Contenedor.setLayout(ContenedorLayout);
        ContenedorLayout.setHorizontalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorLayout.createSequentialGroup()
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContenedorLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(ContenedorLayout.createSequentialGroup()
                                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(39, 39, 39)
                                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(opcionesP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(opcionesP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(opcionesP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ContenedorLayout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(32, 32, 32)
                                    .addComponent(opcionesP6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(ContenedorLayout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(32, 32, 32)
                                    .addComponent(opcionesP8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ContenedorLayout.createSequentialGroup()
                                    .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel14))
                                    .addGap(63, 63, 63)
                                    .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(opcionesP11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(opcionesP10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(opcionesP9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ContenedorLayout.createSequentialGroup()
                                    .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(enviarDatos)
                                        .addComponent(jLabel15))
                                    .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(ContenedorLayout.createSequentialGroup()
                                            .addGap(63, 63, 63)
                                            .addComponent(opcionesP12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(ContenedorLayout.createSequentialGroup()
                                            .addGap(29, 29, 29)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(opcionesP7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(ContenedorLayout.createSequentialGroup()
                                    .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel8))
                                    .addGap(53, 53, 53)
                                    .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(opcionesP5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(opcionesP4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(ContenedorLayout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addComponent(jLabel1)))
                .addContainerGap(303, Short.MAX_VALUE))
        );
        ContenedorLayout.setVerticalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(opcionesP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(opcionesP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(opcionesP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(opcionesP4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(opcionesP5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opcionesP6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opcionesP7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(opcionesP8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opcionesP9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opcionesP10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opcionesP11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opcionesP12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContenedorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContenedorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(enviarDatos)
                        .addGap(34, 34, 34))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcionesP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionesP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcionesP1ActionPerformed

    private void opcionesP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionesP2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcionesP2ActionPerformed

    private void opcionesP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionesP3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcionesP3ActionPerformed

    private void opcionesP4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionesP4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcionesP4ActionPerformed

    private void opcionesP5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionesP5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcionesP5ActionPerformed

    private void opcionesP6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionesP6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcionesP6ActionPerformed

    private void opcionesP7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionesP7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcionesP7ActionPerformed

    private void opcionesP8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionesP8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcionesP8ActionPerformed

    private void opcionesP9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionesP9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcionesP9ActionPerformed

    private void opcionesP10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionesP10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcionesP10ActionPerformed

    private void opcionesP11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionesP11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcionesP11ActionPerformed

    private void opcionesP12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionesP12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcionesP12ActionPerformed

    private void enviarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarDatosActionPerformed
        // TODO add your handling code here:
        int sumaPuntos = 0, SumaPuntos = 0;
        
        sumaPuntos = sumaPuntos + opcionesP1.getSelectedIndex();
        sumaPuntos = sumaPuntos + opcionesP2.getSelectedIndex();
        sumaPuntos = sumaPuntos + opcionesP3.getSelectedIndex();
        sumaPuntos = sumaPuntos + opcionesP4.getSelectedIndex();
        sumaPuntos = sumaPuntos + opcionesP5.getSelectedIndex();
        sumaPuntos = sumaPuntos + opcionesP6.getSelectedIndex();
        sumaPuntos = sumaPuntos + opcionesP7.getSelectedIndex();
        sumaPuntos = sumaPuntos + opcionesP8.getSelectedIndex();
        sumaPuntos = sumaPuntos + opcionesP9.getSelectedIndex();
        sumaPuntos = sumaPuntos + opcionesP10.getSelectedIndex();
        sumaPuntos = sumaPuntos + opcionesP11.getSelectedIndex();
        sumaPuntos = sumaPuntos + opcionesP12.getSelectedIndex();
        SumaPuntos = sumaPuntos;
        /*
        if (sumaPuntos > 27 && sumaPuntos <37 )
            resTipoCuerpo.setText("Tipo de cuerpo ENDOMORFO" + sumaPuntos);
        if (sumaPuntos > 19 && sumaPuntos < 28 )
            resTipoCuerpo.setText("Tipo de cuerpo MESOMORFO" + sumaPuntos);
        if (sumaPuntos > 11 && sumaPuntos <20 )
            resTipoCuerpo.setText("Tipo de cuerpo ECTOMORFO" + sumaPuntos);
        */
        try{
            String conexion= "consult('bd.pl')";
            Query con= new Query(conexion);
            System.out.println(conexion + " " + (con.hasMoreSolutions()? "Aceptado": "False"));
            
            String consulta = "tipoCuerpo(X,"+SumaPuntos+").";
            Query ejecutar = new Query(consulta);
            
            if(ejecutar.hasSolution()){
                resTipoCuerpo.setText("Tipo de cuerpo " + ejecutar.oneSolution().get("X").toString());
                this.tipoCuerpo = ejecutar.oneSolution().get("X").toString();
            }
            else{
                System.out.println("No econtró nada");
                this.tipoCuerpo = "mesomorfo";
            }
            
        }catch(Exception e){
        }
        
    }//GEN-LAST:event_enviarDatosActionPerformed

    public String getTipo(){
        return this.tipoCuerpo;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(testTipoCuerpo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(testTipoCuerpo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(testTipoCuerpo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(testTipoCuerpo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new testTipoCuerpo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenedor;
    private javax.swing.JButton enviarDatos;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> opcionesP1;
    private javax.swing.JComboBox<String> opcionesP10;
    private javax.swing.JComboBox<String> opcionesP11;
    private javax.swing.JComboBox<String> opcionesP12;
    private javax.swing.JComboBox<String> opcionesP2;
    private javax.swing.JComboBox<String> opcionesP3;
    private javax.swing.JComboBox<String> opcionesP4;
    private javax.swing.JComboBox<String> opcionesP5;
    private javax.swing.JComboBox<String> opcionesP6;
    private javax.swing.JComboBox<String> opcionesP7;
    private javax.swing.JComboBox<String> opcionesP8;
    private javax.swing.JComboBox<String> opcionesP9;
    private javax.swing.JTextArea resTipoCuerpo;
    // End of variables declaration//GEN-END:variables
}
